apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval:     5s
      evaluation_interval: 5s

    scrape_configs:

      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'micronaut'
        metrics_path: /prometheus
        static_configs:
        - targets: ['192.10.24.14:31776']






