apiVersion: apps/v1
kind: Deployment
metadata:
# Anotaciones en el change cause de rollout
  annotations:
    kubernetes.io/change-cause: " "
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus-containers
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
            items:
            - key: prometheus.yaml
              path: prometheus.yml

